arrsetcd:
  image: dockerrepo:5000/arrs/arrs-cloud-base-etcd:1.1.0.32
  stdin_open: true
  tty: true
  restart: always
  privileged: true
  ports:
  - "4001:4001"
  - "7001:7001"
  - "2380:2380"
  - "2379:2379"
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
  - ETCD_OUT_FILE=/var/log/etcd/etcd.log
  - ETCD_DATA_DIR=/var/lib/etcd
  - HOST_IP=HOST_IP_MACRO
  - HOST_NAME=HOST_NAME_MACRO
  - IS_LEADER=false
  - MONITOR_PORT=8075
  volumes:
  - /opt/etcd/config:/opt/etcd/config
  - /var/log/etcd:/var/log/etcd
  - /var/lib/etcd:/var/lib/etcd
  - /usr/local/docker/tmp:/tmp
  - /root/tmp2:/tmp2
   
etcdapp:
  image: dockerrepo:5000/arrs/arrs-cloud-base-etcd-app-monitor:1.2.0.13
  stdin_open: true
  tty: true
  restart: always
  privileged: true
  ports:
   - "7500:7500"
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
   - LISTEN_PORT=7500
   - APP_OBSERVER_PORT=8077
   - HOST_IP=HOST_IP_MACRO
   - HOST_NAME=HOST_NAME_MACRO   
  volumes:
   - /usr/sbin:/usr/local/sbin
   - /var/log/app_monitor/etcd:/tmp
   - /var/opt/app-monitor-etcd/perf_monitor/logs:/opt/perf_monitor/logs
   - /var/opt/app-monitor-etcd/status_monitor/logs:/opt/status_monitor/logs
   - /root/tmp2:/tmp2

appObserverEtcd:
  image: dockerrepo:5000/arrs/arrs-cloud-base-app-observer:2.0.0.3
  restart: always
  privileged: true
  ports:
   - "8075:8075"
   - "8077:8077"
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
   - SECURE_PORT=8075
   - NON_SECURE_PORT=8077
   - PRODUCT_NAME=ACP-ETCD
   - APP_WEBSERVICE_FQDN=HOST_IP_MACRO
   - APP_WEBSERVICE_PORT=7500
  volumes:
   - /var/opt/app-observer-etcd/config:/opt/app-observer/conf/external
   - /var/opt/app-observer-etcd/logs:/opt/app-observer/logs   
   
keymanager:
  image: dockerrepo:5000/arrs/arrs-cloud-base-keymanager:1.0.0.9
  stdin_open: true
  tty: true
  restart: always
  privileged: true
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  environment:
  - HOST_IP=HOST_IP_MACRO
  - HOST_NAME=HOST_NAME_MACRO
  volumes:
   - /var/log:/tmp
  volumes_from:
  - arrsetcd
  
logstashforwarder:
  image: dockerrepo:5000/arrs/arrs-cloud-base-logstash-forwarder:2.0.0.4
  restart: always
  privileged: true
  environment:
   LS_HEAP_SIZE: 1g
   CA_CERT_LOCATION: /etc/elk-keys/ca.pem
   ES_HOST: ELK_DNSNAME_MACRO
   NODE_NAME: HOST_IP_MACRO
  log_driver: "json-file"
  log_opt:
   max-size: "100m"
   max-file: "10"
  volumes:
   - /var/opt/logstash-forwarder/log:/var/log/supervisor
   - /var/opt/logstash-forwarder/conf:/etc/logstash-forwarder
   - /var/opt/logstash-forwarder/keys:/etc/elk-keys
   - /etc/localtime:/etc/localtime:ro
   - /var/opt/:/var/opt/
  volumes_from:
   - arrsetcd
