---
- name: Restart haproxy service on haproxy Cluster 
  hosts: zkCluster
  sudo: yes
  sudo_user: root
  
  tasks:
  - name: stop the zookeeper compose file
    command: docker-compose -f /arris/compose/zk-compose.yml stop
    async: 60
    poll: 10   
     
  - name: rm zookeeper 
    command: docker-compose -f /arris/compose/zk-compose.yml rm --force
    async: 60
    poll: 10   
     
  - name: start the zookeeper compose file 
    command: docker-compose -f /arris/compose/zk-compose.yml up -d
   